### ISSUE TITLE
localFiles to config folder

### ISSUE THREAD

**Issue by battery3996** [AllTheMods/ServerStarter#7]
Is it possible to do an entire folder instead of individual files?

EXAMPLE: (how it is now)
```
localFiles:
    - from: localFiles/ftbutilities/player_ranks.txt
      to: local/ftbutilities/player_ranks.txt
    - from: localFiles/ftbutilities/ranks.txt
      to: local/ftbutilities/ranks.txt
    - from: localFiles/ftbutilities/server_badges.txt
      to: local/ftbutilities/server_badges.txt
```

EXAMPLE: (what id like to do if there is alot of configs in one folder)
```
localFiles:
    - from: localFiles/ftbutilities
      to: local/ftbutilities/
```
